improved: move out code of fetching and installing to function
To improve later (add command `fetch`)

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -134,6 +134,124 @@ function checkpackages()
   fi
 }
 
+function fetch_and_install()
+{
+    for pkg in $packages
+    do
+
+    already=`grep -c "^$pkg " /etc/setup/installed.db`
+    if test $already -ge 1
+    then
+      if test $force -eq 0
+      then
+          echo Package $pkg is already installed, skipping
+          continue
+      else
+          echo Package $pkg is already installed but forced reinstall
+      fi
+    fi
+    echo ""
+    echo Installing $pkg
+
+    # look for package and save desc file
+
+    mkdir -p "release/$pkg"
+    cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
+      'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
+       END {if (px == 1 && desc != "") print desc; else print "Package not found"}' 
+    
+    desc=`cat "release/$pkg/desc"`
+    if test "-$desc-" = "-Package not found-"
+    then
+      echo Package $pkg not found or ambiguous name, exiting
+      rm -r "release/$pkg"
+      exit 1
+    fi
+    echo Found package $pkg
+
+    # download and unpack the bz2 file
+
+    # pick the latest version, which comes first
+    install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'` 
+
+    if test "-$install-" = "--"
+    then
+      echo "Could not find \"install\" in package description: obsolete package?"
+      exit 1
+    fi
+
+    file=`basename $install`
+    cd "release/$pkg"
+    wget -nc $mirror/$install
+    
+    # check the md5
+    digest=`cat "desc" | awk '/^install: / { print $4; exit }'` 
+    digactual=`md5sum $file | awk '{print $1}'`
+    if ! test $digest = $digactual
+    then
+      echo MD5 sum did not match, exiting
+      exit 1
+    fi
+    
+    echo "Unpacking..."
+    cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
+    gzip -f "/etc/setup/$pkg.lst"
+    cd ../..
+    
+    
+    # update the package database
+    
+    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
+      "BEGIN{ins=$already} {if (ins < 1 && pkg < \$1) {print pkg \" \" bz \" 0\"; ins=1}; print \$0} \
+       END{if (ins < 1) print pkg \" \" bz \" 0\"}"
+    mv /etc/setup/installed.db /etc/setup/installed.db-save
+    mv /tmp/awk.$$ /etc/setup/installed.db
+    
+    
+    # recursively install required packages
+    
+    echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
+    requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
+    
+    warn=0
+    if ! test "-$requires-" = "--"
+    then
+      echo Package $pkg requires the following packages, installing:
+      echo $requires
+      for package in $requires
+      do
+        already=`grep -c "^$package " /etc/setup/installed.db`
+        if test $already -ge 1
+        then
+          echo Package $package is already installed, skipping
+          continue
+        fi
+        "$APT_CYG" --noscripts install $package
+        if ! test $? = 0 ; then warn=1; fi
+      done
+    fi
+    if ! test $warn = 0
+    then
+      echo "Warning: some required packages did not install, continuing"
+    fi
+    
+    # run all postinstall scripts
+    
+    pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
+    if test $pis -gt 0 && ! test $noscripts -eq 1
+    then
+      echo Running postinstall scripts
+      for script in /etc/postinstall/*.sh
+      do
+        $script
+        mv $script $script.done
+      done
+    fi
+    
+    echo Package $pkg installed
+
+    done
+}
 
 # process options
 
@@ -312,122 +430,7 @@ case "$command" in
     checkpackages
     findworkspace
     getsetup
-
-    for pkg in $packages
-    do
-
-    already=`grep -c "^$pkg " /etc/setup/installed.db`
-    if test $already -ge 1
-    then
-	  if test $force -eq 0
-	  then
-		  echo Package $pkg is already installed, skipping
-		  continue
-	  else
-		  echo Package $pkg is already installed but forced reinstall
-	  fi
-    fi
-    echo ""
-    echo Installing $pkg
-
-    # look for package and save desc file
-
-    mkdir -p "release/$pkg"
-    cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
-      'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
-       END {if (px == 1 && desc != "") print desc; else print "Package not found"}' 
-    
-    desc=`cat "release/$pkg/desc"`
-    if test "-$desc-" = "-Package not found-"
-    then
-      echo Package $pkg not found or ambiguous name, exiting
-      rm -r "release/$pkg"
-      exit 1
-    fi
-    echo Found package $pkg
-
-    # download and unpack the bz2 file
-
-    # pick the latest version, which comes first
-    install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'` 
-
-    if test "-$install-" = "--"
-    then
-      echo "Could not find \"install\" in package description: obsolete package?"
-      exit 1
-    fi
-
-    file=`basename $install`
-    cd "release/$pkg"
-    wget -nc $mirror/$install
-    
-    # check the md5
-    digest=`cat "desc" | awk '/^install: / { print $4; exit }'` 
-    digactual=`md5sum $file | awk '{print $1}'`
-    if ! test $digest = $digactual
-    then
-      echo MD5 sum did not match, exiting
-      exit 1
-    fi
-    
-    echo "Unpacking..."
-    cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
-    gzip -f "/etc/setup/$pkg.lst"
-    cd ../..
-    
-    
-    # update the package database
-    
-    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
-      "BEGIN{ins=$already} {if (ins < 1 && pkg < \$1) {print pkg \" \" bz \" 0\"; ins=1}; print \$0} \
-       END{if (ins < 1) print pkg \" \" bz \" 0\"}"
-    mv /etc/setup/installed.db /etc/setup/installed.db-save
-    mv /tmp/awk.$$ /etc/setup/installed.db
-    
-    
-    # recursively install required packages
-    
-    echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
-    requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
-    
-    warn=0
-    if ! test "-$requires-" = "--"
-    then
-      echo Package $pkg requires the following packages, installing:
-      echo $requires
-      for package in $requires
-      do
-        already=`grep -c "^$package " /etc/setup/installed.db`
-        if test $already -ge 1
-        then
-          echo Package $package is already installed, skipping
-          continue
-        fi
-        "$APT_CYG" --noscripts install $package
-        if ! test $? = 0 ; then warn=1; fi
-      done
-    fi
-    if ! test $warn = 0
-    then
-      echo "Warning: some required packages did not install, continuing"
-    fi
-    
-    # run all postinstall scripts
-    
-    pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
-    if test $pis -gt 0 && ! test $noscripts -eq 1
-    then
-      echo Running postinstall scripts
-      for script in /etc/postinstall/*.sh
-      do
-        $script
-        mv $script $script.done
-      done
-    fi
-    
-    echo Package $pkg installed
-
-    done
+    fetch_and_install 1
 
   ;;
 
