refactoring: code moved out to 'check_dependencies' function

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -19,21 +19,32 @@
 
 # this script requires some packages
 
-WGET=`which wget 2> /dev/null`
-BZIP2=`which bzip2 2> /dev/null`
-TAR=`which tar 2> /dev/null`
-GAWK=`which awk 2> /dev/null`
-if test "-$WGET-" = "--" || test "-$BZIP2-" = "--" || test "-$TAR-" = "--" \
-  || test "-$GAWK-" = "--"
-then
-  echo You must install wget, tar, gawk and bzip2 to use apt-cyg. >&2
-  exit 1
-fi
 APT_CYG="$0"
 if test "${APT_CYG:0:1}" != "/"
 then
 	APT_CYG="$(pwd)/$APT_CYG"
 fi
+
+function check_dependencies
+{
+  DEPENDENCIES="wget bzip2 tar awk"
+
+  deps_ok=YES
+  for dep in $DEPENDENCIES
+  do
+    if ! which $dep &>/dev/null; then
+      echo -e "You must install $dep to use apt-cyg"
+      deps_ok=NO
+    fi
+  done
+
+  if test "$deps_ok" = "NO"; then
+    echo -e "Aborting!"
+    exit 1
+  else
+    return 0
+  fi
+}
 
 function usage()
 {
@@ -493,6 +504,9 @@ command=""
 packages=()
 prefix=""
 wget_options="--no-clobber"
+
+# check apt-cyg dependencies
+check_dependencies
 
 # initialize SETUP_DIR and INSTALLED_DB
 init_vars
