fixed: infinite loop of dependencies
`Bash` packages requires `coreutils` as latter requires former one.

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -273,10 +273,116 @@ function do_postinstall()
     fi
 }
 
+function get_package_desc_file()
+{
+    local pkg="$1"
+    pkg_desc="/tmp/apt-cyg.$pkg.desc"
+    awk < setup.ini > "$pkg_desc" -v package="$pkg" \
+      'BEGIN {
+          RS="\n\n@ ";
+          FS="\n"
+       }
+       {
+           if ($1 == package) {
+               desc = $0;
+               px++
+           }
+       }
+       END {
+           if (px == 1 && desc != "")
+               print desc
+           else
+               print ""
+       }'
+
+    local desc=$(< "$pkg_desc")
+    if test -z "$desc"
+    then
+      echo Package $pkg not found or ambiguous name, exiting >&2
+      rm "$pkg_desc"
+      exit 1
+    fi
+    echo Found package $pkg >&2
+}
+
+function download_package()
+{
+    local pkg_desc="$1"
+
+    # pick the latest version, which comes first
+    local install=$(awk '/^install: / { print $2; exit }' "$pkg_desc")
+
+    if test "-$install-" = "--"
+    then
+      echo "Could not find \"install\" in package description: obsolete package?" >&2
+      rm "$pkg_desc"
+      exit 1
+    fi
+
+    local pkg_dir=$(dirname "$install")
+    # downloaded_file is used later outside
+    downloaded_file=$(basename "$install")
+    mkdir -p "$pkg_dir"
+    pushd "$pkg_dir" 1>/dev/null
+    wget $wget_options $mirror/$install
+
+    # check the md5
+    local digest=$(awk '/^install: / { print $4; exit }' "$pkg_desc")
+    local digactual=$(md5sum $downloaded_file | awk '{print $1}')
+    if ! test "$digest" = "$digactual"
+    then
+      echo MD5 sum did not match, exiting >&2
+      exit 1
+    fi
+}
+
+function array_contains() {
+    local a
+    for a in "${@:2}"; do [[ "$a" == "$1" ]] && return 0; done
+    return 1
+}
+
+function get_requirements_list()
+{
+    local pkg="$1"
+    if test -z "$pkg"
+    then
+        echo "Getting requirements..." >&2
+        for pkg in "${packages[@]}"
+        do
+            get_requirements_list "$pkg"
+        done
+        # comment line below to see requirements only
+        return
+
+        for req in "${requirements[@]}"
+        do
+            echo $req
+        done
+        exit
+
+    else
+        get_package_desc_file "$pkg"
+        # recursively install required packages
+        local requires=$(awk '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}' "$pkg_desc")
+
+        for req in $requires
+        do
+            if ! array_contains "$req" "${requirements[@]}"
+            then
+                requirements[${#requirements[@]}]="$req"
+                get_requirements_list "$req"
+            fi
+        done
+    fi
+}
+
 function fetch_and_install()
 {
-    fetch_only="$1"
-    for pkg in "${packages[@]}"
+    local fetch_only="$1"
+    get_requirements_list
+
+    for pkg in "${requirements[@]}" "${packages[@]}"
     do
 
     if test -z "$fetch_only"
@@ -294,102 +400,26 @@ function fetch_and_install()
         fi
         echo ""
     fi
-    echo Fetching $pkg
 
     # look for package and save desc file
+    # download the bz2 file
+    get_package_desc_file "$pkg"
 
-    pkg_desc="/tmp/apt-cyg.$pkg.desc"
-    awk < setup.ini > "$pkg_desc" -v package="$pkg" \
-      'BEGIN {
-          RS="\n\n@ ";
-          FS="\n"
-       }
-       {
-           if ($1 == package) {
-               desc = $0;
-               px++
-           }
-       }
-       END {
-           if (px == 1 && desc != "")
-               print desc
-           else
-               print "Package not found"
-       }'
+    echo Fetching $pkg
 
-    desc=$(< "$pkg_desc")
-    if test "-$desc-" = "-Package not found-"
-    then
-      echo Package $pkg not found or ambiguous name, exiting >&2
-      rm "$pkg_desc"
-      exit 1
-    fi
-    echo Found package $pkg
-
-    # download and unpack the bz2 file
-
-    # pick the latest version, which comes first
-    install=$(awk '/^install: / { print $2; exit }' "$pkg_desc")
-
-    if test "-$install-" = "--"
-    then
-      echo "Could not find \"install\" in package description: obsolete package?" >&2
-      rm "$pkg_desc"
-      exit 1
-    fi
-
-    pkg_dir=$(dirname "$install")
-    file=$(basename "$install")
-    mkdir -p "$pkg_dir"
-    pushd "$pkg_dir" 1>/dev/null
-    wget $wget_options $mirror/$install
-
-    # check the md5
-    digest=$(awk '/^install: / { print $4; exit }' "$pkg_desc")
-    digactual=$(md5sum $file | awk '{print $1}')
-    if ! test "$digest" = "$digactual"
-    then
-      echo MD5 sum did not match, exiting >&2
-      exit 1
-    fi
-
-    # recursively install required packages
-    requires=$(awk '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}' "$pkg_desc")
-
-    warn=0
-    if ! test "-$requires-" = "--"
-    then
-      echo Package $pkg requires the following packages, installing:
-      echo $requires
-      for package in $requires
-      do
-        already=$(grep -c "^$package " $INSTALLED_DB)
-        if test "$already" -ge 1
-        then
-          if test -z "$force"
-          then
-              echo Package $package is already installed, skipping
-              continue
-          else
-              echo Package $package is already installed but forced reinstall
-          fi
-        fi
-        "$APT_CYG" --prefix "$prefix" --noscripts install $fetch_only $force $package
-        if ! test $? = 0 ; then warn=1; fi
-      done
-    fi
-    if ! test $warn = 0
-    then
-      echo "Warning: some required packages were not installed, continuing"
-    fi
+    download_package "$pkg_desc"
 
     if test -n "$fetch_only"
     then
+        # pushd is in `download_package`
         popd 1>/dev/null
+        rm "$pkg_desc"
         continue
     fi
 
-    unpack "$file"
+    # unpack the bz2 file
+    unpack "$downloaded_file"
+    # pushd is in `download_package`
     popd 1>/dev/null
 
     # update the package database
@@ -574,6 +604,7 @@ packages=()
 prefix=""
 wget_options="--no-clobber"
 arch=""
+requirements=()
 
 # check apt-cyg dependencies
 check_dependencies
